/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemosRouteImport } from './routes/_memos'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MemosIndexRouteImport } from './routes/_memos/index'
import { Route as MemosExploreRouteImport } from './routes/_memos/explore'
import { Route as MemosAboutRouteImport } from './routes/_memos/about'
import { Route as MemosProtectedRouteImport } from './routes/_memos/_protected'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MemosUUsernameRouteImport } from './routes/_memos/u/$username'
import { Route as MemosProtectedSettingsRouteImport } from './routes/_memos/_protected/settings'
import { Route as MemosProtectedInboxRouteImport } from './routes/_memos/_protected/inbox'
import { Route as MemosProtectedHomeRouteImport } from './routes/_memos/_protected/home'
import { Route as MemosProtectedAttachmentsRouteImport } from './routes/_memos/_protected/attachments'
import { Route as MemosProtectedArchivedRouteImport } from './routes/_memos/_protected/archived'

const MemosRoute = MemosRouteImport.update({
  id: '/_memos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosIndexRoute = MemosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemosRoute,
} as any)
const MemosExploreRoute = MemosExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MemosRoute,
} as any)
const MemosAboutRoute = MemosAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MemosRoute,
} as any)
const MemosProtectedRoute = MemosProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => MemosRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosUUsernameRoute = MemosUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => MemosRoute,
} as any)
const MemosProtectedSettingsRoute = MemosProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MemosProtectedRoute,
} as any)
const MemosProtectedInboxRoute = MemosProtectedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => MemosProtectedRoute,
} as any)
const MemosProtectedHomeRoute = MemosProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MemosProtectedRoute,
} as any)
const MemosProtectedAttachmentsRoute =
  MemosProtectedAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => MemosProtectedRoute,
  } as any)
const MemosProtectedArchivedRoute = MemosProtectedArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => MemosProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MemosIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about': typeof MemosAboutRoute
  '/explore': typeof MemosExploreRoute
  '/archived': typeof MemosProtectedArchivedRoute
  '/attachments': typeof MemosProtectedAttachmentsRoute
  '/home': typeof MemosProtectedHomeRoute
  '/inbox': typeof MemosProtectedInboxRoute
  '/settings': typeof MemosProtectedSettingsRoute
  '/u/$username': typeof MemosUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof MemosIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about': typeof MemosAboutRoute
  '/explore': typeof MemosExploreRoute
  '/archived': typeof MemosProtectedArchivedRoute
  '/attachments': typeof MemosProtectedAttachmentsRoute
  '/home': typeof MemosProtectedHomeRoute
  '/inbox': typeof MemosProtectedInboxRoute
  '/settings': typeof MemosProtectedSettingsRoute
  '/u/$username': typeof MemosUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_memos': typeof MemosRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_memos/_protected': typeof MemosProtectedRouteWithChildren
  '/_memos/about': typeof MemosAboutRoute
  '/_memos/explore': typeof MemosExploreRoute
  '/_memos/': typeof MemosIndexRoute
  '/_memos/_protected/archived': typeof MemosProtectedArchivedRoute
  '/_memos/_protected/attachments': typeof MemosProtectedAttachmentsRoute
  '/_memos/_protected/home': typeof MemosProtectedHomeRoute
  '/_memos/_protected/inbox': typeof MemosProtectedInboxRoute
  '/_memos/_protected/settings': typeof MemosProtectedSettingsRoute
  '/_memos/u/$username': typeof MemosUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/explore'
    | '/archived'
    | '/attachments'
    | '/home'
    | '/inbox'
    | '/settings'
    | '/u/$username'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/explore'
    | '/archived'
    | '/attachments'
    | '/home'
    | '/inbox'
    | '/settings'
    | '/u/$username'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_memos'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_memos/_protected'
    | '/_memos/about'
    | '/_memos/explore'
    | '/_memos/'
    | '/_memos/_protected/archived'
    | '/_memos/_protected/attachments'
    | '/_memos/_protected/home'
    | '/_memos/_protected/inbox'
    | '/_memos/_protected/settings'
    | '/_memos/u/$username'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MemosRoute: typeof MemosRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_memos': {
      id: '/_memos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_memos/': {
      id: '/_memos/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MemosIndexRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/explore': {
      id: '/_memos/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MemosExploreRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/about': {
      id: '/_memos/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MemosAboutRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/_protected': {
      id: '/_memos/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemosProtectedRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_memos/u/$username': {
      id: '/_memos/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof MemosUUsernameRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/_protected/settings': {
      id: '/_memos/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MemosProtectedSettingsRouteImport
      parentRoute: typeof MemosProtectedRoute
    }
    '/_memos/_protected/inbox': {
      id: '/_memos/_protected/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof MemosProtectedInboxRouteImport
      parentRoute: typeof MemosProtectedRoute
    }
    '/_memos/_protected/home': {
      id: '/_memos/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MemosProtectedHomeRouteImport
      parentRoute: typeof MemosProtectedRoute
    }
    '/_memos/_protected/attachments': {
      id: '/_memos/_protected/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof MemosProtectedAttachmentsRouteImport
      parentRoute: typeof MemosProtectedRoute
    }
    '/_memos/_protected/archived': {
      id: '/_memos/_protected/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof MemosProtectedArchivedRouteImport
      parentRoute: typeof MemosProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MemosProtectedRouteChildren {
  MemosProtectedArchivedRoute: typeof MemosProtectedArchivedRoute
  MemosProtectedAttachmentsRoute: typeof MemosProtectedAttachmentsRoute
  MemosProtectedHomeRoute: typeof MemosProtectedHomeRoute
  MemosProtectedInboxRoute: typeof MemosProtectedInboxRoute
  MemosProtectedSettingsRoute: typeof MemosProtectedSettingsRoute
}

const MemosProtectedRouteChildren: MemosProtectedRouteChildren = {
  MemosProtectedArchivedRoute: MemosProtectedArchivedRoute,
  MemosProtectedAttachmentsRoute: MemosProtectedAttachmentsRoute,
  MemosProtectedHomeRoute: MemosProtectedHomeRoute,
  MemosProtectedInboxRoute: MemosProtectedInboxRoute,
  MemosProtectedSettingsRoute: MemosProtectedSettingsRoute,
}

const MemosProtectedRouteWithChildren = MemosProtectedRoute._addFileChildren(
  MemosProtectedRouteChildren,
)

interface MemosRouteChildren {
  MemosProtectedRoute: typeof MemosProtectedRouteWithChildren
  MemosAboutRoute: typeof MemosAboutRoute
  MemosExploreRoute: typeof MemosExploreRoute
  MemosIndexRoute: typeof MemosIndexRoute
  MemosUUsernameRoute: typeof MemosUUsernameRoute
}

const MemosRouteChildren: MemosRouteChildren = {
  MemosProtectedRoute: MemosProtectedRouteWithChildren,
  MemosAboutRoute: MemosAboutRoute,
  MemosExploreRoute: MemosExploreRoute,
  MemosIndexRoute: MemosIndexRoute,
  MemosUUsernameRoute: MemosUUsernameRoute,
}

const MemosRouteWithChildren = MemosRoute._addFileChildren(MemosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MemosRoute: MemosRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
