/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemosRouteImport } from './routes/_memos'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MemosSettingsRouteImport } from './routes/_memos/settings'
import { Route as MemosInboxRouteImport } from './routes/_memos/inbox'
import { Route as MemosHomeRouteImport } from './routes/_memos/home'
import { Route as MemosExploreRouteImport } from './routes/_memos/explore'
import { Route as MemosAttachmentsRouteImport } from './routes/_memos/attachments'
import { Route as MemosArchivedRouteImport } from './routes/_memos/archived'
import { Route as MemosAboutRouteImport } from './routes/_memos/about'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MemosUUsernameRouteImport } from './routes/_memos/u/$username'

const MemosRoute = MemosRouteImport.update({
  id: '/_memos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosSettingsRoute = MemosSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MemosRoute,
} as any)
const MemosInboxRoute = MemosInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => MemosRoute,
} as any)
const MemosHomeRoute = MemosHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MemosRoute,
} as any)
const MemosExploreRoute = MemosExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MemosRoute,
} as any)
const MemosAttachmentsRoute = MemosAttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => MemosRoute,
} as any)
const MemosArchivedRoute = MemosArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => MemosRoute,
} as any)
const MemosAboutRoute = MemosAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MemosRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosUUsernameRoute = MemosUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => MemosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MemosRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about': typeof MemosAboutRoute
  '/archived': typeof MemosArchivedRoute
  '/attachments': typeof MemosAttachmentsRoute
  '/explore': typeof MemosExploreRoute
  '/home': typeof MemosHomeRoute
  '/inbox': typeof MemosInboxRoute
  '/settings': typeof MemosSettingsRoute
  '/u/$username': typeof MemosUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof MemosRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about': typeof MemosAboutRoute
  '/archived': typeof MemosArchivedRoute
  '/attachments': typeof MemosAttachmentsRoute
  '/explore': typeof MemosExploreRoute
  '/home': typeof MemosHomeRoute
  '/inbox': typeof MemosInboxRoute
  '/settings': typeof MemosSettingsRoute
  '/u/$username': typeof MemosUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_memos': typeof MemosRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_memos/about': typeof MemosAboutRoute
  '/_memos/archived': typeof MemosArchivedRoute
  '/_memos/attachments': typeof MemosAttachmentsRoute
  '/_memos/explore': typeof MemosExploreRoute
  '/_memos/home': typeof MemosHomeRoute
  '/_memos/inbox': typeof MemosInboxRoute
  '/_memos/settings': typeof MemosSettingsRoute
  '/_memos/u/$username': typeof MemosUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/archived'
    | '/attachments'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/settings'
    | '/u/$username'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/archived'
    | '/attachments'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/settings'
    | '/u/$username'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_memos'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_memos/about'
    | '/_memos/archived'
    | '/_memos/attachments'
    | '/_memos/explore'
    | '/_memos/home'
    | '/_memos/inbox'
    | '/_memos/settings'
    | '/_memos/u/$username'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MemosRoute: typeof MemosRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_memos': {
      id: '/_memos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_memos/settings': {
      id: '/_memos/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MemosSettingsRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/inbox': {
      id: '/_memos/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof MemosInboxRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/home': {
      id: '/_memos/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MemosHomeRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/explore': {
      id: '/_memos/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MemosExploreRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/attachments': {
      id: '/_memos/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof MemosAttachmentsRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/archived': {
      id: '/_memos/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof MemosArchivedRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/about': {
      id: '/_memos/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MemosAboutRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_memos/u/$username': {
      id: '/_memos/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof MemosUUsernameRouteImport
      parentRoute: typeof MemosRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MemosRouteChildren {
  MemosAboutRoute: typeof MemosAboutRoute
  MemosArchivedRoute: typeof MemosArchivedRoute
  MemosAttachmentsRoute: typeof MemosAttachmentsRoute
  MemosExploreRoute: typeof MemosExploreRoute
  MemosHomeRoute: typeof MemosHomeRoute
  MemosInboxRoute: typeof MemosInboxRoute
  MemosSettingsRoute: typeof MemosSettingsRoute
  MemosUUsernameRoute: typeof MemosUUsernameRoute
}

const MemosRouteChildren: MemosRouteChildren = {
  MemosAboutRoute: MemosAboutRoute,
  MemosArchivedRoute: MemosArchivedRoute,
  MemosAttachmentsRoute: MemosAttachmentsRoute,
  MemosExploreRoute: MemosExploreRoute,
  MemosHomeRoute: MemosHomeRoute,
  MemosInboxRoute: MemosInboxRoute,
  MemosSettingsRoute: MemosSettingsRoute,
  MemosUUsernameRoute: MemosUUsernameRoute,
}

const MemosRouteWithChildren = MemosRoute._addFileChildren(MemosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MemosRoute: MemosRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
