/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemosRouteImport } from './routes/_memos'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MemosIndexRouteImport } from './routes/_memos/index'
import { Route as MemosSearchRouteImport } from './routes/_memos/_search'
import { Route as MemosBareRouteImport } from './routes/_memos/_bare'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MemosSearchExploreRouteImport } from './routes/_memos/_search/explore'
import { Route as MemosSearchProtectedRouteImport } from './routes/_memos/_search/_protected'
import { Route as MemosBareAboutRouteImport } from './routes/_memos/_bare/about'
import { Route as MemosBareProtectedRouteImport } from './routes/_memos/_bare/_protected'
import { Route as MemosSearchUUsernameRouteImport } from './routes/_memos/_search/u/$username'
import { Route as MemosSearchProtectedHomeRouteImport } from './routes/_memos/_search/_protected/home'
import { Route as MemosSearchProtectedArchivedRouteImport } from './routes/_memos/_search/_protected/archived'
import { Route as MemosBareProtectedSettingsRouteImport } from './routes/_memos/_bare/_protected/settings'
import { Route as MemosBareProtectedInboxRouteImport } from './routes/_memos/_bare/_protected/inbox'
import { Route as MemosBareProtectedAttachmentsRouteImport } from './routes/_memos/_bare/_protected/attachments'

const MemosRoute = MemosRouteImport.update({
  id: '/_memos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosIndexRoute = MemosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemosRoute,
} as any)
const MemosSearchRoute = MemosSearchRouteImport.update({
  id: '/_search',
  getParentRoute: () => MemosRoute,
} as any)
const MemosBareRoute = MemosBareRouteImport.update({
  id: '/_bare',
  getParentRoute: () => MemosRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosSearchExploreRoute = MemosSearchExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MemosSearchRoute,
} as any)
const MemosSearchProtectedRoute = MemosSearchProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => MemosSearchRoute,
} as any)
const MemosBareAboutRoute = MemosBareAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MemosBareRoute,
} as any)
const MemosBareProtectedRoute = MemosBareProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => MemosBareRoute,
} as any)
const MemosSearchUUsernameRoute = MemosSearchUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => MemosSearchRoute,
} as any)
const MemosSearchProtectedHomeRoute =
  MemosSearchProtectedHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => MemosSearchProtectedRoute,
  } as any)
const MemosSearchProtectedArchivedRoute =
  MemosSearchProtectedArchivedRouteImport.update({
    id: '/archived',
    path: '/archived',
    getParentRoute: () => MemosSearchProtectedRoute,
  } as any)
const MemosBareProtectedSettingsRoute =
  MemosBareProtectedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MemosBareProtectedRoute,
  } as any)
const MemosBareProtectedInboxRoute = MemosBareProtectedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => MemosBareProtectedRoute,
} as any)
const MemosBareProtectedAttachmentsRoute =
  MemosBareProtectedAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => MemosBareProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MemosIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about': typeof MemosBareAboutRoute
  '/explore': typeof MemosSearchExploreRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/attachments': typeof MemosBareProtectedAttachmentsRoute
  '/inbox': typeof MemosBareProtectedInboxRoute
  '/settings': typeof MemosBareProtectedSettingsRoute
  '/archived': typeof MemosSearchProtectedArchivedRoute
  '/home': typeof MemosSearchProtectedHomeRoute
  '/u/$username': typeof MemosSearchUUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof MemosIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/about': typeof MemosBareAboutRoute
  '/explore': typeof MemosSearchExploreRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/attachments': typeof MemosBareProtectedAttachmentsRoute
  '/inbox': typeof MemosBareProtectedInboxRoute
  '/settings': typeof MemosBareProtectedSettingsRoute
  '/archived': typeof MemosSearchProtectedArchivedRoute
  '/home': typeof MemosSearchProtectedHomeRoute
  '/u/$username': typeof MemosSearchUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_memos': typeof MemosRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_memos/_bare': typeof MemosBareRouteWithChildren
  '/_memos/_search': typeof MemosSearchRouteWithChildren
  '/_memos/': typeof MemosIndexRoute
  '/_memos/_bare/_protected': typeof MemosBareProtectedRouteWithChildren
  '/_memos/_bare/about': typeof MemosBareAboutRoute
  '/_memos/_search/_protected': typeof MemosSearchProtectedRouteWithChildren
  '/_memos/_search/explore': typeof MemosSearchExploreRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/_memos/_bare/_protected/attachments': typeof MemosBareProtectedAttachmentsRoute
  '/_memos/_bare/_protected/inbox': typeof MemosBareProtectedInboxRoute
  '/_memos/_bare/_protected/settings': typeof MemosBareProtectedSettingsRoute
  '/_memos/_search/_protected/archived': typeof MemosSearchProtectedArchivedRoute
  '/_memos/_search/_protected/home': typeof MemosSearchProtectedHomeRoute
  '/_memos/_search/u/$username': typeof MemosSearchUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/explore'
    | '/api/auth/$'
    | '/api/files/$'
    | '/attachments'
    | '/inbox'
    | '/settings'
    | '/archived'
    | '/home'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/explore'
    | '/api/auth/$'
    | '/api/files/$'
    | '/attachments'
    | '/inbox'
    | '/settings'
    | '/archived'
    | '/home'
    | '/u/$username'
  id:
    | '__root__'
    | '/_auth'
    | '/_memos'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_memos/_bare'
    | '/_memos/_search'
    | '/_memos/'
    | '/_memos/_bare/_protected'
    | '/_memos/_bare/about'
    | '/_memos/_search/_protected'
    | '/_memos/_search/explore'
    | '/api/auth/$'
    | '/api/files/$'
    | '/_memos/_bare/_protected/attachments'
    | '/_memos/_bare/_protected/inbox'
    | '/_memos/_bare/_protected/settings'
    | '/_memos/_search/_protected/archived'
    | '/_memos/_search/_protected/home'
    | '/_memos/_search/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MemosRoute: typeof MemosRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_memos': {
      id: '/_memos'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_memos/': {
      id: '/_memos/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MemosIndexRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/_search': {
      id: '/_memos/_search'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemosSearchRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_memos/_bare': {
      id: '/_memos/_bare'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemosBareRouteImport
      parentRoute: typeof MemosRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_memos/_search/explore': {
      id: '/_memos/_search/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MemosSearchExploreRouteImport
      parentRoute: typeof MemosSearchRoute
    }
    '/_memos/_search/_protected': {
      id: '/_memos/_search/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemosSearchProtectedRouteImport
      parentRoute: typeof MemosSearchRoute
    }
    '/_memos/_bare/about': {
      id: '/_memos/_bare/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MemosBareAboutRouteImport
      parentRoute: typeof MemosBareRoute
    }
    '/_memos/_bare/_protected': {
      id: '/_memos/_bare/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemosBareProtectedRouteImport
      parentRoute: typeof MemosBareRoute
    }
    '/_memos/_search/u/$username': {
      id: '/_memos/_search/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof MemosSearchUUsernameRouteImport
      parentRoute: typeof MemosSearchRoute
    }
    '/_memos/_search/_protected/home': {
      id: '/_memos/_search/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MemosSearchProtectedHomeRouteImport
      parentRoute: typeof MemosSearchProtectedRoute
    }
    '/_memos/_search/_protected/archived': {
      id: '/_memos/_search/_protected/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof MemosSearchProtectedArchivedRouteImport
      parentRoute: typeof MemosSearchProtectedRoute
    }
    '/_memos/_bare/_protected/settings': {
      id: '/_memos/_bare/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MemosBareProtectedSettingsRouteImport
      parentRoute: typeof MemosBareProtectedRoute
    }
    '/_memos/_bare/_protected/inbox': {
      id: '/_memos/_bare/_protected/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof MemosBareProtectedInboxRouteImport
      parentRoute: typeof MemosBareProtectedRoute
    }
    '/_memos/_bare/_protected/attachments': {
      id: '/_memos/_bare/_protected/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof MemosBareProtectedAttachmentsRouteImport
      parentRoute: typeof MemosBareProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MemosBareProtectedRouteChildren {
  MemosBareProtectedAttachmentsRoute: typeof MemosBareProtectedAttachmentsRoute
  MemosBareProtectedInboxRoute: typeof MemosBareProtectedInboxRoute
  MemosBareProtectedSettingsRoute: typeof MemosBareProtectedSettingsRoute
}

const MemosBareProtectedRouteChildren: MemosBareProtectedRouteChildren = {
  MemosBareProtectedAttachmentsRoute: MemosBareProtectedAttachmentsRoute,
  MemosBareProtectedInboxRoute: MemosBareProtectedInboxRoute,
  MemosBareProtectedSettingsRoute: MemosBareProtectedSettingsRoute,
}

const MemosBareProtectedRouteWithChildren =
  MemosBareProtectedRoute._addFileChildren(MemosBareProtectedRouteChildren)

interface MemosBareRouteChildren {
  MemosBareProtectedRoute: typeof MemosBareProtectedRouteWithChildren
  MemosBareAboutRoute: typeof MemosBareAboutRoute
}

const MemosBareRouteChildren: MemosBareRouteChildren = {
  MemosBareProtectedRoute: MemosBareProtectedRouteWithChildren,
  MemosBareAboutRoute: MemosBareAboutRoute,
}

const MemosBareRouteWithChildren = MemosBareRoute._addFileChildren(
  MemosBareRouteChildren,
)

interface MemosSearchProtectedRouteChildren {
  MemosSearchProtectedArchivedRoute: typeof MemosSearchProtectedArchivedRoute
  MemosSearchProtectedHomeRoute: typeof MemosSearchProtectedHomeRoute
}

const MemosSearchProtectedRouteChildren: MemosSearchProtectedRouteChildren = {
  MemosSearchProtectedArchivedRoute: MemosSearchProtectedArchivedRoute,
  MemosSearchProtectedHomeRoute: MemosSearchProtectedHomeRoute,
}

const MemosSearchProtectedRouteWithChildren =
  MemosSearchProtectedRoute._addFileChildren(MemosSearchProtectedRouteChildren)

interface MemosSearchRouteChildren {
  MemosSearchProtectedRoute: typeof MemosSearchProtectedRouteWithChildren
  MemosSearchExploreRoute: typeof MemosSearchExploreRoute
  MemosSearchUUsernameRoute: typeof MemosSearchUUsernameRoute
}

const MemosSearchRouteChildren: MemosSearchRouteChildren = {
  MemosSearchProtectedRoute: MemosSearchProtectedRouteWithChildren,
  MemosSearchExploreRoute: MemosSearchExploreRoute,
  MemosSearchUUsernameRoute: MemosSearchUUsernameRoute,
}

const MemosSearchRouteWithChildren = MemosSearchRoute._addFileChildren(
  MemosSearchRouteChildren,
)

interface MemosRouteChildren {
  MemosBareRoute: typeof MemosBareRouteWithChildren
  MemosSearchRoute: typeof MemosSearchRouteWithChildren
  MemosIndexRoute: typeof MemosIndexRoute
}

const MemosRouteChildren: MemosRouteChildren = {
  MemosBareRoute: MemosBareRouteWithChildren,
  MemosSearchRoute: MemosSearchRouteWithChildren,
  MemosIndexRoute: MemosIndexRoute,
}

const MemosRouteWithChildren = MemosRoute._addFileChildren(MemosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MemosRoute: MemosRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
